/*
 * MainFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.licence.swing;

import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.licence.util.DesUtils;


/**
 *
 * @author  __USER__
 */
public class MainFrame extends javax.swing.JFrame {

	/** Creates new form MainFrame */
	public MainFrame() {
		initComponents();
		this.setLocation(500, 300);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
//GEN-BEGIN:initComponents
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {

jDialog1 = new javax.swing.JDialog();
jLabel1 = new javax.swing.JLabel();
jTextField1 = new javax.swing.JTextField();
jLabel2 = new javax.swing.JLabel();
jTextField2 = new javax.swing.JTextField();
jLabel3 = new javax.swing.JLabel();
jTextField3 = new javax.swing.JTextField();
button1 = new java.awt.Button();
button2 = new java.awt.Button();

javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
jDialog1.getContentPane().setLayout(jDialog1Layout);
jDialog1Layout.setHorizontalGroup(
jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGap(0, 400, Short.MAX_VALUE)
);
jDialog1Layout.setVerticalGroup(
jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGap(0, 300, Short.MAX_VALUE)
);

setDefaultCloseOperation(3);

jLabel1.setText("\u8bf7\u8f93\u5165\u60a8\u7684\u5bc6\u94a5");

jTextField1.setName("keyTextFiled");

jLabel2.setText("\u8bf7\u8f93\u5165\u516c\u53f8\u540d\u79f0");

jTextField2.setName("keyTextFiled");

jLabel3.setText("\u8bf7\u8f93\u5165\u6570\u91cf");

jTextField3.setName("keyTextFiled");

button1.setLabel("\u786e\u5b9a");
button1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
button1ActionPerformed(evt);
}
});

button2.setLabel("\u5173\u95ed");
button2.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
button2ActionPerformed(evt);
}
});

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(28, 28, 28)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(jTextField1)
.addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
.addGroup(layout.createSequentialGroup()
.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jTextField3))))
.addGroup(layout.createSequentialGroup()
.addGap(69, 69, 69)
.addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(28, 28, 28)
.addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addContainerGap(20, Short.MAX_VALUE))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(28, 28, 28)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(25, 25, 25))
);

pack();
}// </editor-fold>
//GEN-END:initComponents

	private void button2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void button1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.out.println("开始加密....");
		String key = this.jTextField1.getText();
		if (key == null || key.trim().equals("")) {
			//JOptionPane.
			MyDialog dialog = new MyDialog(this, true,"请输入密钥");
			dialog.setVisible(true);
			dialog.setAlertResult("请输入密钥");
			return;
		}
		String company = this.jTextField2.getText();
		if (company == null || company.trim().equals("")) {
			MyDialog dialog = new MyDialog(this, true,"请输入公司英文名称");
			dialog.setAlertResult("请输入公司英文名称");
			dialog.setVisible(true);
			return;
		}
		String num = this.jTextField3.getText();
		if (num == null || num.trim().equals("")) {
			MyDialog dialog = new MyDialog(this, true,"请输入数量");
			dialog.setVisible(true);
			dialog.setAlertResult("请输入数量");
			return;
		} else {
			Pattern pattern = Pattern.compile("[0-9]*");
			Matcher match = pattern.matcher(num);
			if (!match.matches()) {
				MyDialog dialog = new MyDialog(this, true,"请输入正确的数字");
				dialog.setVisible(true);
				dialog.setAlertResult("请输入正确的数字");
				return;
			}
		}
		SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");
		Date date = new Date();
		String fileName = sf.format(date) + "-" + num + "-"
				+ System.currentTimeMillis() + ".dat";
		this.createFile(fileName, key, company, num);
		System.out.println("加密结束....");
	}

	public boolean createFile(String path, String key, String company,
			String num) {
		
		try {
		DesUtils des = new DesUtils();
		System.out.println("加密key= " + key);
		String miKey=des.encrypt(key);
		System.out.println("加密后的key= "+miKey);
		String oppoKey="key:"+key;
		oppoKey=des.encrypt(oppoKey);
		System.out.println("对KEY再次加密(key:"+key+") = "+oppoKey);
		DesUtils des1=new DesUtils(miKey);
		//Crypt c = new Crypt(miKey);
		
		
			
			String res = "num:" + num;
			res = des1.encrypt(res);
			System.out.println("第一次加密数量(num:" + num + ") = " + res);
			String com = "company:oppo";
			com=des1.encrypt(com);
			System.out.println("第一次加密公司名称(company:oppo) = " + com);
			String all=oppoKey+","+com+","+res;
			all=des.encrypt(all);
			System.out.println("全部加密为 " + all);
			//开始生成文件
			File f=new File("D:\\licence");   
			 if(!f.exists()){   
			   f.mkdirs();   
			  }   

			File file = new File("D:\\licence\\" + path);
			if (!file.exists()) {
				file.createNewFile();
				file.canWrite();
			}
			FileOutputStream fos = new FileOutputStream(file);
			byte[] b = all.getBytes("UTF-8");
			fos.write(b);
			fos.flush();
			fos.close();
			MyDialog dialog = new MyDialog(this, true,"正确生成licence,路径为D:\\licence\\");
			dialog.setVisible(true);
			dialog.setAlertResult("请输入正确的数字");
			/*
			System.out.println("开始解密......");
			String mi = "67e48eb5642b4384b85c04cf54da98e41fa239db96de3bb56ead67b24dc8f9a1526127fe974342e132039d748a464dc20423d1408d2a8b5493f6b59005e4d14124a2bf6525114c4e3890ad366d73672444a9a7348a4f815f";
			String firstMing=des.decrypt(mi);
			System.out.println("第一次解密="+firstMing);
			String[] split=firstMing.split(",");
			System.out.println("开始分段解密");
			String mingKey=des.decrypt(split[0]);
			System.out.println("解密后的key="+mingKey);
			String[] mingKeys=mingKey.split(":");
			key=mingKeys[1];
			key=des.encrypt(key);
			System.out.println("真正的加密key="+key);
			DesUtils desMing=new DesUtils(key);
			String mingCom=desMing.decrypt(split[1]);
			System.out.println("分段解密的company= "+mingCom);
			String[] mingComs=mingCom.split(":");
			System.out.println("分段解密的company= "+mingComs[1]);
			String mingNum=desMing.decrypt(split[2]);
			System.out.println("分段解密的num= "+mingNum);
			String[] mingNums=mingNum.split(":");
			System.out.println("分段解密的num= "+mingNums[1]);
			*/
//			String ming = c.getDecryptedString(mi);
//			System.out.println("第一次解密明文= " + ming);
//			File file = new File("D:\\licence\\" + path);
//			if (!file.exists()) {
//				file.createNewFile();
//				file.canWrite();
//			}
//			FileOutputStream fos = new FileOutputStream(file);
//			byte[] b = resultMi.getBytes("UTF-8");
//			fos.write(b);
//			fos.flush();
//			fos.close();

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return true;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
//		String licence="67e48eb5642b4384b85c04cf54da98e41fa239db96de3bb56ead67b24dc8f9a1526127fe974342e132039d748a464dc20423d1408d2a8b5493f6b59005e4d14124a2bf6525114c4e3890ad366d73672444a9a7348a4f815f";
//		try {
//			DesUtils defaultDes=new DesUtils();
//			String firstMing=defaultDes.decrypt(licence);
//			String[] split=firstMing.split(",");
//			if(split==null||split.length!=3)
//			{
//				System.out.println("解密出错");
//				return;
//			}
//			String keyMing=defaultDes.decrypt(split[0]);
//			String key=keyMing.split(":")[1];
//			System.out.println("解密后的原始key= "+key);
//			key=defaultDes.encrypt(key);
//			System.out.println("使用的key= "+key);
//			DesUtils des=new DesUtils(key);
//			String mingCom=des.decrypt(split[1]);
//			System.out.println("解密后的公司信息= "+mingCom);
//			String mingNum=des.decrypt(split[2]);
//			System.out.println("解密后的数量="+mingNum);
//			
//		} catch (Exception e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//		

	}

//GEN-BEGIN:variables
// Variables declaration - do not modify
private java.awt.Button button1;
private java.awt.Button button2;
private javax.swing.JDialog jDialog1;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JTextField jTextField1;
private javax.swing.JTextField jTextField2;
private javax.swing.JTextField jTextField3;
// End of variables declaration//GEN-END:variables

}